### ISSUE TITLE
SCF unconverged in gamess

### ISSUE THREAD

**Issue by yaqun** [AlbertDeFusco/molden2gamess#1]
Hi Dr. Defusco,
I just tried to use gamess to do the SPE calculation with wavefunctions from turbomole included, but it is not converged. The basis set used is def2-SVP. The directory is /home/jkeith/yaz59/molden2gamess/tests/ozone/Yaqun_test. Could you help me to check why it is not converged?
Additionally, I tried doing the same work based on yours in /home/jkeith/yaz59/molden2gamess/tests/ozone/cct . The SCF energy is converged after 9 iterations.
Best,
Yaqun

**Comment by AlbertDeFusco** [comment]
There are several discrepancies between your Turbomole and GAMESS input files. I'm glad that you chose a hard problem.

## Spin

The Turbomole calculation you ran determined that ozone is a triplet state. GAMESS will by default run a singlet state. Add the following keyword to the GAMESS input.

```
$contrl mult=3 $end
```

## DFT Method

In order to use B3LYP with the D3 dispersion correction you need the following keywords in GAMESS.

```
$contrl dfttyp=b3lyp $end
$dft dc=.t. dcver=3 $end
```

## GAMESS

If you were to attempt to calculate the triplet unrestricted B3YP-D3/def2-SVP energy without reading the orbitals GAMESS will fail. You can do this by running the conversion script, adding the appropriate keywords above for spin and DFT, but remove the `$GUESS` keywords. After 30 iterations GAMESS will not converge the wavefunction.

```
  29 28     -190.7687047719    -4.9307861661   5.323445581   2.046388444
  30 29     -178.1982913121    12.5704134597   5.230542504   2.012928061

 SCF IS UNCONVERGED, TOO MANY ITERATIONS
....
FINAL U-B3LYP ENERGY IS        0.0000000000 AFTER  30 ITERATIONS
DFT EXCHANGE + CORRELATION ENERGY =       -21.7352231003
TOTAL ELECTRON NUMBER             =        24.0000012474
GRIMME'S DISPERSION ENERGY                     =       -0.0001427627
ENERGY WITHOUT GRIMME'S DISPERSION CORRECTION IS        0.0000000000
```

## Converted orbitals

When all of the above keywords are in place along with the `$DATA` and `$GUESS` groups from the converter script, then it takes 14 iterations, but it <b>will converge</b> to the right energy and spin.

```
  14 13     -225.0969189325     0.0000000000   0.000000788   0.000000375

          -----------------
          DENSITY CONVERGED
          -----------------
....
 FINAL U-B3LYP ENERGY IS     -225.0970616951 AFTER  14 ITERATIONS
 DFT EXCHANGE + CORRELATION ENERGY =       -20.5294908366
 TOTAL ELECTRON NUMBER             =        24.0000003845
 GRIMME'S DISPERSION ENERGY                     =       -0.0001427627
 ENERGY WITHOUT GRIMME'S DISPERSION CORRECTION IS     -225.0969189325

          --------------------
          SPIN SZ   =    1.000
          S-SQUARED =    2.014
          --------------------
```

**Comment by AlbertDeFusco** [comment]
For your file in `/home/jkeith/yaz59/molden2gamess/tests/ozone/cct` you neglected to use the `-t` flag.

**Comment by yaqun** [comment]
Hi Dr. Defusco,
Thank you for your help.
The following are the results for ozone.

After  -t added in the command, the SCF energy is converged after 4
iterations.
In addition, after the keywords added in the input file with B3LYP-D3 in
/home/jkeith/yaz59/molden2gamess/tests/ozone/Yaqun_test, the SCF energy is
converged after 14 iterations.

Best,
Yaqun

**Comment by AlbertDeFusco** [comment]
Yaqun,

That is correct. I would recommend that you keep practicing with other molecules, DFT methods and basis sets.

Albert

**Comment by yaqun** [comment]
Hi Dr. DeFusco,
Based on the turbomole calculation results with cc-pVTZ as basis sets for
all atoms and HAY/WADT (N-1) ECP for Co, the Gamess calculation with the
same basis sets and ECP met a problem and the calculation cannot be done in
"2 ELECTRON INTEGRALS".
Could you help me with it?
The directory
is /home/jkeith/yaz59/molden2gamess/tests/Co_complex/cct_ecp_turbo_ecpgamess.
Best,
Yaqun

**Comment by AlbertDeFusco** [comment]
Yaqun,

Have you tried the direct integral?

$scf dirscf=.t. $end

Albert

**Comment by SACHA-1982** [comment]
i am running morokuma decomposition energy using gamess, but it doesn 't work, it telle me scf unconverged too many iterations
thank you for the help

**Comment by AlbertDeFusco** [comment]
Are you using this script to convert orbitals first or just running Morokuma using the guess orbitals?

**Comment by SACHA-1982** [comment]
no iam not using a script, i run morokuma directly

Date: Thu, 24 Mar 2016 12:43:19 -0700

**Comment by AlbertDeFusco** [comment]
I would suggest that you contact someone at [Iowa State](http://www.msg.chem.iastate.edu/) for help.
